name: Build Releases
on:
  push:
    # limit to main branch
    branches: [master]
permissions:
  contents: write
jobs:
  release:
    name: Release on ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    env:
      RUST_BIN_NAME: "tree"
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            suffix: .exe
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            suffix: .exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # fix revision count
          fetch-depth: '0'
      - uses: Swatinem/rust-cache@v2
        with:
          # The prefix cache key, this can be changed to start a new cache manually.
          # default: "v0-rust"
          prefix-key: ${{ matrix.target }}
          shared-key: "main"
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true
      - name: Prepare assets
        shell: bash
        run: |
          mv target/${{ matrix.target }}/release/${{ env.RUST_BIN_NAME }}${{ matrix.suffix }} .
          tar -cvzf ${{ matrix.target }}.tar.gz LICENSE README.md ${{ env.RUST_BIN_NAME }}${{ matrix.suffix }}
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          rev_count=$(git rev-list --count HEAD)
          echo rev_count=${rev_count} >> $GITHUB_OUTPUT
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.target }}.tar.gz
          tag_name: r${{ steps.vars.outputs.rev_count }}
          prerelease: false
          make_latest: true
